// import Head from 'next/head'
// import Image from 'next/image'
// import styles from '../Home.module.css'
import HomeIcon from '@mui/icons-material/Home'
import { useForm, SubmitHandler } from 'react-hook-form'

type MyFormData = {
  firstName: string
  lastName: string
  category: string
}

type HomeIconProps = {
  fontSize?: string
  color?: string
}

const HomeIconComponent = ({ fontSize, color }: HomeIconProps) => (
  <span style={{ fontSize, color }}>
    <HomeIcon fontSize="inherit" color="inherit" />
  </span>
)

export default function Home() {
  const {
    register,
    handleSubmit,
    formState: { errors },
  } = useForm<MyFormData>()
  const onSubmit: SubmitHandler<MyFormData> = (data) => {
    console.log(data)
  }

  return (
    <>
      <div>
        <HomeIconComponent />
        <HomeIconComponent fontSize="22px" color="#3f51b5" />
      </div>
      <form onSubmit={handleSubmit(onSubmit)}>
        <input
          {...register('firstName', { required: true })}
          placeholder="名前"
        />
        <div>{errors.firstName && <p>名前を入力してください</p>}</div>
        <input
          {...register('lastName', { required: true })}
          placeholder="名字"
        />
        <div>{errors.lastName && <p>名字を入力してください</p>}</div>
        <select {...register('category', { required: true })}>
          <option value="">選択...</option>
          <option value="A">カテゴリA</option>
          <option value="B">カテゴリB</option>
        </select>
        <div>{errors.category && <p>カテゴリを選択してください</p>}</div>
        <input type="submit" />
      </form>
    </>
  )
}

// export default function Home() {
//   return (
//     <div className={styles.container}>
//       <Head>
//         <title>Create Next App</title>
//         <meta name="description" content="Generated by create next app" />
//         <link rel="icon" href="/favicon.ico" />
//       </Head>

//       <main className={styles.main}>
//         <h1 className={styles.title}>
//           Welcome to <a href="https://nextjs.org">Next.js!</a>
//         </h1>

//         <p className={styles.description}>
//           Get started by editing{' '}
//           <code className={styles.code}>pages/index.tsx</code>
//         </p>

//         <div className={styles.grid}>
//           <a href="https://nextjs.org/docs" className={styles.card}>
//             <h2>Documentation &rarr;</h2>
//             <p>Find in-depth information about Next.js features and API.</p>
//           </a>

//           <a href="https://nextjs.org/learn" className={styles.card}>
//             <h2>Learn &rarr;</h2>
//             <p>Learn about Next.js in an interactive course with quizzes!</p>
//           </a>

//           <a
//             href="https://github.com/vercel/next.js/tree/canary/examples"
//             className={styles.card}
//           >
//             <h2>Examples &rarr;</h2>
//             <p>Discover and deploy boilerplate example Next.js projects.</p>
//           </a>

//           <a
//             href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//             target="_blank"
//             rel="noopener noreferrer"
//             className={styles.card}
//           >
//             <h2>Deploy &rarr;</h2>
//             <p>
//               Instantly deploy your Next.js site to a public URL with Vercel.
//             </p>
//           </a>
//         </div>
//       </main>

//       <footer className={styles.footer}>
//         <a
//           href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
//           target="_blank"
//           rel="noopener noreferrer"
//         >
//           Powered by{' '}
//           <span className={styles.logo}>
//             <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
//           </span>
//         </a>
//       </footer>
//     </div>
//   )
// }
